services:
  next-app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm run build && npm start"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - next-app
